"""Face registry: decides 'existing person' vs 'new person' and registers new ones.

Flow for one (already averaged) embedding:

    best_match(embedding) -> (face_id, similarity)
    similarity >= threshold  -> existing Face ID, nothing is written
    otherwise                -> new Face ID is generated BY THE DATABASE,
                                embedding + image + metadata are stored,
                                the in-memory gallery is updated immediately.

Because the gallery is updated immediately, two tracks of the same new person
resolved a moment apart cannot both register.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Optional

import numpy as np

from app.database.sqlite_repository import SQLiteRepository
from app.errors import DatabaseError, ImageStorageError
from app.event_logging import event_logger as ev
from app.event_logging.event_logger import EventLogger
from app.models import format_wall_time
from app.recognition.face_matcher import FaceMatcher, normalize
from app.storage.image_store import ImageStore


@dataclass
class IdentityResult:
    face_id: str
    similarity: float
    is_new: bool


class FaceRegistry:
    def __init__(self, repository: SQLiteRepository, matcher: FaceMatcher,
                 image_store: ImageStore, logger: EventLogger,
                 similarity_threshold: float) -> None:
        self._repo = repository
        self._matcher = matcher
        self._images = image_store
        self._log = logger
        self.threshold = similarity_threshold

    @classmethod
    def load(cls, repository: SQLiteRepository, image_store: ImageStore,
             logger: EventLogger, similarity_threshold: float) -> "FaceRegistry":
        """Build a registry whose gallery contains every face already in the DB."""
        matcher = FaceMatcher()
        for face_id, embedding in repository.load_embeddings():
            matcher.add(face_id, embedding)
        return cls(repository, matcher, image_store, logger, similarity_threshold)

    @property
    def registered_count(self) -> int:
        return self._matcher.size

    def identify_or_register(self, embedding: np.ndarray, crop: Optional[np.ndarray],
                             when: datetime, track_id: Optional[int] = None) -> IdentityResult:
        embedding = normalize(embedding)
        face_id, similarity = self._matcher.best_match(embedding)
        if face_id is not None and similarity >= self.threshold:
            return IdentityResult(face_id, similarity, is_new=False)
        closest = similarity if face_id is not None else None   # None when the gallery was empty
        return self._register(embedding, crop, when, track_id, closest)

    def _register(self, embedding: np.ndarray, crop: Optional[np.ndarray], when: datetime,
                  track_id: Optional[int], best_similarity: Optional[float]) -> IdentityResult:
        face_id = self._repo.create_face(embedding, format_wall_time(when))  # may raise DatabaseError
        self._matcher.add(face_id, embedding)
        image_path = None
        if crop is not None:
            try:
                image_path = self._images.save_registration(face_id, crop, when)
                self._repo.set_representative_image(face_id, image_path)
            except ImageStorageError as exc:
                self._log.error(ev.IMAGE_ERROR, face_id=face_id, error=str(exc))
            except DatabaseError as exc:
                self._log.error(ev.DATABASE_ERROR, operation="set_representative_image",
                                face_id=face_id, error=str(exc))
        fields = {"face_id": face_id, "track_id": track_id, "image": image_path or "none"}
        if best_similarity is not None:
            fields["closest_existing_similarity"] = best_similarity
        self._log.info(ev.FACE_REGISTERED, **fields)
        return IdentityResult(face_id, -1.0 if best_similarity is None else best_similarity, is_new=True)
